# Use the official Node.js LTS version as a parent image
FROM node:lts-alpine

# Set the working directory in the Docker image
WORKDIR /app

# Copy package.json and package-lock.json (if available) to the Docker image
COPY package*.json ./

# Install application dependencies inside the Docker image
RUN npm install

# Copy the rest of the application files to the Docker image
COPY . .

# Expose port 5173, which is the default port for VITE, for the server
EXPOSE 5173

# At runtime, serve the application on port 5173
CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]