version: '3.8'
services:
  backend:
    build: ./server
    container_name: covid19-statistics-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  frontend:
    build: ./client
    container_name: covid19-statistics-frontend
    environment:
      - VITE_APP_API_BASE_URL=http://localhost:8000
    ports:
      - 8080:5173