# Use the official Python 3.8 image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the Docker image
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run the command to start Uvicorn with live-reloading enabled
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]